### ISSUE TITLE
LiDAR SLAM & Localizer Survey

### ISSUE THREAD

**Issue by TakanoTaiga** [hakoroboken/roboware-neo.universe#4]
3D LiDARを使用したSLAMとLocalizerについてサーベイする。

## TODO
- [ ] NDT Scan Matchingについて理解する
- [ ] lidarslam_ros2の屋内&屋外で使えるパラメータを検証する
- [ ] lidar_localization_ros2も同様に検証
- [ ] 必要に応じてROSBagを収集する
